name: Process Translation Queue

on:
  schedule:
    # 毎時実行（必要に応じて頻度を調整）
    - cron: '0 * * * *'
  workflow_dispatch: # 手動実行も可能

jobs:
  process-translations:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Process translation queue
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
      run: npm run process-translations
    
    - name: Log results
      if: always()
      run: |
        echo "Translation processing completed at $(date)"