name: Process Translation Queue

on:
  schedule:
    # 毎時実行（バックアップ）
    - cron: '0 * * * *'
  workflow_dispatch: # 手動実行とAPI経由の実行
    inputs:
      listing_id:
        description: 'Specific listing ID to translate (optional)'
        required: false
        type: string

jobs:
  process-translations:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Process translation queue
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        SPECIFIC_LISTING_ID: ${{ github.event.inputs.listing_id }}
      run: npm run process-translations
    
    - name: Log results
      if: always()
      run: |
        echo "Translation processing completed at $(date)"